import { supabase } from './config/supabase';

const products = [
  // ELECTRONICS (20 products)
  { name: 'Wireless Noise-Cancelling Headphones Pro', description: 'Premium over-ear headphones with active noise cancellation, 40-hour battery life, and crystal-clear sound quality. Features adaptive ANC, transparency mode, and comfortable memory foam ear cushions.', price: 249.99, compare_price: 329.99, images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600', 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600'], brand: 'SoundPro', count_in_stock: 45, rating: 4.5, num_reviews: 12453, features: ['Active Noise Cancellation', '40-hour battery', 'Memory foam cushions', 'Bluetooth 5.2'], is_featured: true },
  { name: 'SmartWatch Pro X2 - Fitness Tracker', description: 'Advanced smartwatch with health monitoring, GPS tracking, 14-day battery life, and water resistance. Track your heart rate, sleep, and workouts with precision.', price: 199.99, compare_price: 259.99, images: ['https://images.unsplash.com/photo-1546868871-af0de0ae72a5?w=600', 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600'], brand: 'TechWear', count_in_stock: 78, rating: 4.3, num_reviews: 8765, features: ['Heart rate monitoring', 'GPS tracking', '14-day battery'], is_featured: true },
  { name: '4K Ultra HD Smart TV 55" - HDR10+', description: 'Stunning 4K resolution with HDR10+ support. Smart platform with built-in streaming apps, voice control, and Dolby Atmos sound. Perfect for movie nights and gaming.', price: 549.99, compare_price: 699.99, images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600', 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600'], brand: 'ViewTech', count_in_stock: 23, rating: 4.6, num_reviews: 4521, features: ['4K HDR10+', 'Dolby Atmos', 'Smart TV', 'Voice Control'], is_featured: true },
  { name: 'Wireless Bluetooth Earbuds - ANC', description: 'True wireless earbuds with active noise cancellation. 8 hours playtime, IPX5 water resistance, and premium sound quality with deep bass.', price: 79.99, compare_price: 99.99, images: ['https://images.unsplash.com/photo-1590658268037-6bf12f032f75?w=600'], brand: 'SoundPro', count_in_stock: 180, rating: 4.3, num_reviews: 15432, features: ['Active Noise Cancellation', 'IPX5 Water Resistant', '8hr Battery'], is_featured: true },
  { name: 'Mechanical Gaming Keyboard RGB', description: 'RGB mechanical keyboard with Cherry MX switches. Aircraft-grade aluminum frame, programmable macro keys, and per-key RGB lighting.', price: 129.99, compare_price: 169.99, images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600'], brand: 'GameTech', count_in_stock: 88, rating: 4.5, num_reviews: 6789, features: ['Cherry MX Switches', 'RGB Per Key', 'Aluminum Frame'], is_featured: true },
  { name: 'Wireless Gaming Mouse - 16000 DPI', description: 'Ultra-lightweight wireless gaming mouse with 16000 DPI sensor, 80-hour battery, and customizable RGB lighting. Perfect for competitive gaming.', price: 69.99, compare_price: 89.99, images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600'], brand: 'GameTech', count_in_stock: 120, rating: 4.4, num_reviews: 5432, features: ['16000 DPI', '80hr Battery', 'Ultra-light 58g'], is_featured: false },
  { name: 'USB-C Hub 7-in-1 Multiport Adapter', description: '7-in-1 USB-C hub with HDMI 4K, 3 USB 3.0 ports, SD/TF card reader, and 100W PD charging. Compatible with MacBook, iPad Pro, and laptops.', price: 34.99, compare_price: 49.99, images: ['https://images.unsplash.com/photo-1626285861696-400c3b83fb47?w=600'], brand: 'ConnectPro', count_in_stock: 200, rating: 4.2, num_reviews: 3210, features: ['HDMI 4K Output', '100W PD Charging', 'SD Card Reader'], is_featured: false },
  { name: 'Portable Bluetooth Speaker - Waterproof', description: 'Rugged portable Bluetooth speaker with IP67 waterproof rating, 24-hour battery, and powerful 360-degree sound. Perfect for outdoor adventures.', price: 59.99, compare_price: 79.99, images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600'], brand: 'SoundPro', count_in_stock: 95, rating: 4.5, num_reviews: 8765, features: ['IP67 Waterproof', '24hr Battery', '360 Sound'], is_featured: false },
  { name: '27" 4K Monitor - IPS Panel', description: 'Professional 27" 4K IPS monitor with 99% sRGB, HDR400, and USB-C connectivity. Ideal for designers, developers, and content creators.', price: 399.99, compare_price: 499.99, images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600'], brand: 'ViewTech', count_in_stock: 34, rating: 4.6, num_reviews: 2345, features: ['4K IPS Panel', '99% sRGB', 'USB-C 65W'], is_featured: false },
  { name: 'Laptop Stand - Ergonomic Aluminum', description: 'Adjustable aluminum laptop stand with ergonomic design. Improves posture and airflow. Compatible with all laptops 10-17 inches.', price: 29.99, compare_price: 39.99, images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600'], brand: 'ErgoGear', count_in_stock: 150, rating: 4.3, num_reviews: 4567, features: ['Height Adjustable', 'Aluminum Build', 'Anti-Slip'], is_featured: false },
  { name: 'Portable SSD 1TB - USB 3.2', description: 'Ultra-fast portable SSD with 1050MB/s read speed. Pocket-sized, shock-resistant, and compatible with PC, Mac, and PlayStation.', price: 89.99, compare_price: 129.99, images: ['https://images.unsplash.com/photo-1603202655044-3dec4ab31e33?w=600'], brand: 'StorageMax', count_in_stock: 67, rating: 4.7, num_reviews: 6543, features: ['1050MB/s Read', '1TB Capacity', 'Shock Resistant'], is_featured: false },
  { name: 'Webcam 4K - Auto Focus with Mic', description: 'Professional 4K webcam with auto-focus, built-in ring light, and noise-cancelling microphone. Perfect for streaming and video conferencing.', price: 79.99, compare_price: 99.99, images: ['https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=600'], brand: 'ClearView', count_in_stock: 55, rating: 4.2, num_reviews: 3456, features: ['4K Resolution', 'Auto Focus', 'Built-in Ring Light'], is_featured: false },
  { name: 'Smart Plug - WiFi Voice Control', description: 'Smart WiFi plug compatible with Alexa and Google Home. Schedule devices, monitor energy usage, and control from anywhere.', price: 14.99, compare_price: 24.99, images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600'], brand: 'SmartLife', count_in_stock: 300, rating: 4.1, num_reviews: 9876, features: ['Alexa & Google', 'Energy Monitor', 'Schedule Timer'], is_featured: false },
  { name: 'Wireless Charger Pad - Fast Charge', description: '15W fast wireless charger pad with Qi compatibility. Slim design with LED indicator and foreign object detection.', price: 19.99, compare_price: 29.99, images: ['https://images.unsplash.com/photo-1586816879360-004f5b5c2e4c?w=600'], brand: 'ChargeFast', count_in_stock: 210, rating: 4.0, num_reviews: 6543, features: ['15W Fast Charge', 'Qi Compatible', 'LED Indicator'], is_featured: false },
  { name: 'iPad Pro 12.9" Case - Premium Leather', description: 'Premium leather case with magnetic closure, Apple Pencil holder, and multiple viewing angles. Slim profile with drop protection.', price: 39.99, compare_price: 49.99, images: ['https://images.unsplash.com/photo-1564069114553-7215e1ff1890?w=600'], brand: 'ArmorCase', count_in_stock: 85, rating: 4.3, num_reviews: 2345, features: ['Genuine Leather', 'Pencil Holder', 'Drop Protection'], is_featured: false },
  { name: 'Noise Cancelling Earbuds - Sleep Edition', description: 'Ultra-compact wireless earbuds designed for sleep. Block snoring with ANC, play sleep sounds, and comfortable for side sleepers.', price: 149.99, compare_price: 179.99, images: ['https://images.unsplash.com/photo-1594678051903-85f482f220ba?w=600'], brand: 'SleepSound', count_in_stock: 40, rating: 4.4, num_reviews: 5678, features: ['Sleep ANC', 'Side Sleeper', 'Sleep Sounds'], is_featured: false },
  { name: 'Dash Camera 4K - Front and Rear', description: 'Dual-channel dash camera with 4K front and 1080p rear recording. Night vision, parking mode, and GPS tracking.', price: 129.99, compare_price: 169.99, images: ['https://images.unsplash.com/photo-1589496933730-25933e6b0224?w=600'], brand: 'DriveCam', count_in_stock: 62, rating: 4.5, num_reviews: 4321, features: ['4K Front + 1080p Rear', 'Night Vision', 'GPS Tracking'], is_featured: false },
  { name: 'Power Bank 20000mAh - Fast Charging', description: 'High-capacity 20000mAh power bank with 65W PD fast charging. Charge laptops, tablets, and phones simultaneously.', price: 49.99, compare_price: 69.99, images: ['https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600'], brand: 'ChargeFast', count_in_stock: 175, rating: 4.4, num_reviews: 7890, features: ['20000mAh', '65W PD', 'Charge 3 Devices'], is_featured: false },
  { name: 'Gaming Headset - 7.1 Surround Sound', description: 'Premium gaming headset with 7.1 surround sound, noise-cancelling mic, RGB lighting, and memory foam ear cushions.', price: 59.99, compare_price: 79.99, images: ['https://images.unsplash.com/photo-1599669454699-248893623440?w=600'], brand: 'GameTech', count_in_stock: 90, rating: 4.3, num_reviews: 5432, features: ['7.1 Surround', 'Noise Cancelling Mic', 'RGB Lighting'], is_featured: false },
  { name: 'Tablet 10" - Android 14 WiFi', description: '10-inch Android tablet with 2K display, octa-core processor, 6GB RAM, 128GB storage. Perfect for entertainment and productivity.', price: 179.99, compare_price: 229.99, images: ['https://images.unsplash.com/photo-1587033411391-5d9e51cce126?w=600'], brand: 'TechPad', count_in_stock: 48, rating: 4.1, num_reviews: 3456, features: ['2K Display', '128GB Storage', 'Android 14'], is_featured: false },
  // FASHION (17 products)
  { name: 'Premium Cotton Casual Shirt', description: '100% organic cotton casual shirt with regular fit. Comfortable for daily wear with breathable fabric and classic design.', price: 39.99, compare_price: 59.99, images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600'], brand: 'UrbanStyle', count_in_stock: 150, rating: 4.2, num_reviews: 3210, features: ['100% Organic Cotton', 'Regular Fit', 'Machine Washable'], is_featured: true },
  { name: 'Designer Leather Jacket - Genuine Leather', description: 'Premium genuine leather jacket with modern design. Features zippered pockets, quilted lining, and adjustable waist. A timeless wardrobe essential.', price: 189.99, compare_price: 249.99, images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600'], brand: 'EliteWear', count_in_stock: 35, rating: 4.4, num_reviews: 1876, features: ['Genuine Leather', 'Zippered Pockets', 'Quilted Lining'], is_featured: true },
  { name: 'Athletic Running Shoes - Ultra Comfort', description: 'Lightweight running shoes with responsive cushioning, breathable mesh upper, and durable outsole. Perfect for daily runs and workouts.', price: 89.99, compare_price: 119.99, images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600'], brand: 'FlexFit', count_in_stock: 200, rating: 4.5, num_reviews: 8765, features: ['Responsive Cushioning', 'Breathable Mesh', 'Durable Outsole'], is_featured: false },
  { name: 'Classic Denim Jacket - Vintage Wash', description: 'Timeless denim jacket in vintage wash. Features button front, chest pockets, and adjustable waist tabs. A wardrobe essential for all seasons.', price: 69.99, compare_price: 89.99, images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600'], brand: 'DenimCo', count_in_stock: 80, rating: 4.3, num_reviews: 4567, features: ['Vintage Wash', 'Button Front', 'Adjustable Waist'], is_featured: false },
  { name: 'Summer Dress - Floral Print', description: 'Beautiful floral print summer dress with flowy fit. Made from lightweight, breathable fabric perfect for warm weather.', price: 34.99, compare_price: 49.99, images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600'], brand: 'UrbanStyle', count_in_stock: 120, rating: 4.1, num_reviews: 2345, features: ['Floral Print', 'Lightweight', 'Flowy Fit'], is_featured: false },
  { name: 'Men\'s Formal Suit - Slim Fit', description: 'Sharp slim-fit formal suit in premium wool-blend fabric. Includes jacket and trousers. Perfect for business and formal occasions.', price: 199.99, compare_price: 299.99, images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600'], brand: 'EliteWear', count_in_stock: 45, rating: 4.6, num_reviews: 3456, features: ['Wool-Blend', 'Slim Fit', '2-Piece Suit'], is_featured: false },
  { name: 'Winter Parka - Insulated Down Jacket', description: 'Warm insulated parka with down filling, detachable hood, and water-resistant outer shell. Rated for extreme cold temperatures.', price: 149.99, compare_price: 199.99, images: ['https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600'], brand: 'NorthEdge', count_in_stock: 65, rating: 4.7, num_reviews: 5678, features: ['Down Insulated', 'Detachable Hood', 'Water Resistant'], is_featured: false },
  { name: 'Cashmere Sweater - Luxury Knit', description: 'Luxurious 100% cashmere sweater in classic crew neck design. Incredibly soft, warm, and lightweight. Machine washable for easy care.', price: 129.99, compare_price: 169.99, images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600'], brand: 'LuxeKnit', count_in_stock: 55, rating: 4.5, num_reviews: 2345, features: ['100% Cashmere', 'Crew Neck', 'Machine Washable'], is_featured: false },
  { name: 'Cargo Pants - Multi-Pocket', description: 'Durable cargo pants with multiple pockets, reinforced knees, and adjustable cuffs. Perfect for outdoor activities and casual wear.', price: 49.99, compare_price: 64.99, images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600'], brand: 'UrbanStyle', count_in_stock: 90, rating: 4.2, num_reviews: 4567, features: ['Multi-Pocket', 'Reinforced Knees', 'Adjustable Cuffs'], is_featured: false },
  { name: 'Silk Tie - Designer Collection', description: 'Handcrafted silk tie from premium Italian silk. Classic width with subtle pattern. Adds elegance to any formal ensemble.', price: 39.99, compare_price: 59.99, images: ['https://images.unsplash.com/photo-1589756823695-278bc923f962?w=600'], brand: 'EliteWear', count_in_stock: 110, rating: 4.0, num_reviews: 1234, features: ['Italian Silk', 'Handcrafted', 'Classic Width'], is_featured: false },
  { name: 'Leather Belt - Premium Cowhide', description: 'Full-grain cowhide leather belt with brushed nickel buckle. 35mm width, classic design that pairs with any outfit.', price: 29.99, compare_price: 44.99, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'], brand: 'EliteWear', count_in_stock: 200, rating: 4.3, num_reviews: 6789, features: ['Full-Grain Leather', 'Nickel Buckle', '35mm Width'], is_featured: false },
  { name: 'Sunglasses - Polarized UV400', description: 'Stylish polarized sunglasses with UV400 protection. Lightweight titanium frame with scratch-resistant lenses.', price: 59.99, compare_price: 89.99, images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600'], brand: 'VisionPro', count_in_stock: 75, rating: 4.4, num_reviews: 3456, features: ['Polarized', 'UV400', 'Titanium Frame'], is_featured: false },
  { name: 'Wool Scarf - Premium Merino', description: 'Luxurious merino wool scarf in classic plaid pattern. Extra-long design for versatile styling. Incredibly soft and warm.', price: 44.99, compare_price: 59.99, images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600'], brand: 'LuxeKnit', count_in_stock: 85, rating: 4.5, num_reviews: 2345, features: ['Merino Wool', 'Plaid Pattern', 'Extra Long'], is_featured: false },
  { name: 'Canvas Backpack - Vintage Style', description: 'Vintage-style canvas backpack with leather trim. Padded laptop compartment, multiple pockets, and comfortable straps.', price: 54.99, compare_price: 74.99, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'], brand: 'UrbanStyle', count_in_stock: 130, rating: 4.2, num_reviews: 4567, features: ['Canvas + Leather', 'Laptop Compartment', 'Multi-Pocket'], is_featured: false },
  { name: 'Leather Wallet - RFID Blocking', description: 'Slim leather wallet with RFID blocking technology. 8 card slots, ID window, and bill compartment. Genuine cowhide leather.', price: 34.99, compare_price: 49.99, images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=600'], brand: 'EliteWear', count_in_stock: 160, rating: 4.3, num_reviews: 5678, features: ['RFID Blocking', '8 Card Slots', 'Genuine Leather'], is_featured: false },
  { name: 'Hoodie - Premium Fleece', description: 'Premium heavyweight fleece hoodie with adjustable drawstring hood, kangaroo pocket, and ribbed cuffs. Ultra-soft and warm.', price: 59.99, compare_price: 79.99, images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600'], brand: 'UrbanStyle', count_in_stock: 190, rating: 4.4, num_reviews: 7890, features: ['Heavyweight Fleece', 'Adjustable Hood', 'Kangaroo Pocket'], is_featured: false },
  // HOME & KITCHEN (16 products)
  { name: 'Professional Chef Knife Set - 8 Piece', description: '8-piece professional kitchen knife set with high-carbon stainless steel. Includes chef knife, bread knife, utility knife, paring knife, and sharpening rod.', price: 89.99, compare_price: 129.99, images: ['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600'], brand: 'ChefMaster', count_in_stock: 67, rating: 4.7, num_reviews: 6543, features: ['High-carbon Stainless Steel', 'Ergonomic Handles', 'Includes Sharpening Rod'], is_featured: true },
  { name: 'Non-Stick Cookware Set - 12 Piece', description: 'Complete 12-piece non-stick cookware set with ceramic coating. Includes pots, pans, lids, and utensils. Dishwasher and oven safe.', price: 149.99, compare_price: 199.99, images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600'], brand: 'KitchenPro', count_in_stock: 45, rating: 4.5, num_reviews: 4567, features: ['Ceramic Non-Stick', 'Dishwasher Safe', 'Oven Safe to 450F'], is_featured: false },
  { name: 'Air Fryer - Digital 5.8qt', description: 'Digital air fryer with 5.8qt capacity, 8 presets, and shake reminder. Cook crispy food with 95% less oil. Includes recipe book.', price: 79.99, compare_price: 109.99, images: ['https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600'], brand: 'KitchenPro', count_in_stock: 89, rating: 4.5, num_reviews: 12345, features: ['5.8qt Capacity', '8 Presets', '95% Less Oil'], is_featured: false },
  { name: 'Stand Mixer - 5 Quart', description: 'Powerful 5-quart stand mixer with 12 speeds, tilt-head design, and included attachments. Perfect for baking and cooking enthusiasts.', price: 199.99, compare_price: 279.99, images: ['https://images.unsplash.com/photo-1594226801341-41427b4c5f0d?w=600'], brand: 'ChefMaster', count_in_stock: 32, rating: 4.6, num_reviews: 7890, features: ['5-Quart Bowl', '12 Speeds', 'Tilt-Head Design'], is_featured: false },
  { name: 'Coffee Maker - Programmable 12 Cup', description: 'Programmable 12-cup coffee maker with thermal carafe, brew strength selector, and auto-shutoff. Make perfect coffee every morning.', price: 49.99, compare_price: 69.99, images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600'], brand: 'BrewMaster', count_in_stock: 120, rating: 4.3, num_reviews: 5678, features: ['12-Cup Thermal Carafe', 'Programmable Timer', 'Brew Strength'], is_featured: false },
  { name: 'Espresso Machine - Semi-Automatic', description: 'Semi-automatic espresso machine with 15-bar pressure system, milk frother, and temperature control. Make cafe-quality espresso at home.', price: 299.99, compare_price: 399.99, images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600'], brand: 'BrewMaster', count_in_stock: 28, rating: 4.7, num_reviews: 3456, features: ['15-Bar Pressure', 'Milk Frother', 'Temperature Control'], is_featured: false },
  { name: 'Robot Vacuum - Smart Mapping', description: 'Smart robot vacuum with LiDAR navigation, 2500Pa suction, and app control. Maps your home for efficient cleaning. Works with Alexa.', price: 249.99, compare_price: 349.99, images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600'], brand: 'SmartHome', count_in_stock: 56, rating: 4.4, num_reviews: 6789, features: ['LiDAR Navigation', '2500Pa Suction', 'App Control'], is_featured: false },
  { name: 'Bed Sheet Set - 100% Egyptian Cotton', description: 'Luxury 1000-thread-count Egyptian cotton bed sheet set. Includes fitted sheet, flat sheet, and 2 pillowcases. Silky smooth and breathable.', price: 89.99, compare_price: 129.99, images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600'], brand: 'HomeLuxe', count_in_stock: 95, rating: 4.6, num_reviews: 8901, features: ['1000 Thread Count', 'Egyptian Cotton', '4-Piece Set'], is_featured: false },
  { name: 'Bath Towel Set - Premium Cotton', description: 'Premium 6-piece bath towel set in 100% Turkish cotton. Includes 2 bath towels, 2 hand towels, and 2 washcloths. Ultra-soft and absorbent.', price: 44.99, compare_price: 64.99, images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600'], brand: 'HomeLuxe', count_in_stock: 140, rating: 4.3, num_reviews: 4567, features: ['Turkish Cotton', '6-Piece Set', 'Ultra-Soft'], is_featured: false },
  { name: 'Smart LED Bulb - WiFi Color Changing', description: 'WiFi smart LED bulb with 16 million colors, dimmable, and voice control. Compatible with Alexa and Google Home. Set schedules and scenes.', price: 12.99, compare_price: 19.99, images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600'], brand: 'SmartLife', count_in_stock: 260, rating: 4.1, num_reviews: 12345, features: ['16M Colors', 'Alexa & Google', 'Dimmable'], is_featured: false },
  { name: 'Kitchen Blender - 1500W', description: 'Professional-grade 1500W blender with 64oz pitcher, 10 speeds, and pulse function. Crush ice, blend smoothies, and puree soups.', price: 69.99, compare_price: 89.99, images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600'], brand: 'KitchenPro', count_in_stock: 78, rating: 4.4, num_reviews: 5678, features: ['1500W Motor', '64oz Pitcher', '10 Speeds'], is_featured: false },
  { name: 'Storage Organizer Set - Modular', description: 'Modular storage organizer set with 12 stackable bins. Perfect for closets, pantry, and garage. Clear design with label holders.', price: 39.99, compare_price: 54.99, images: ['https://images.unsplash.com/photo-1602872030490-5e1b5e0f1a9b?w=600'], brand: 'HomeLuxe', count_in_stock: 110, rating: 4.2, num_reviews: 3456, features: ['12 Bins', 'Stackable', 'Label Holders'], is_featured: false },
  { name: 'Indoor Plant Pot Set - Ceramic', description: 'Set of 3 ceramic plant pots with drainage holes and bamboo trays. Modern minimalist design in matte finish. Various sizes.', price: 34.99, compare_price: 49.99, images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600'], brand: 'GreenHome', count_in_stock: 85, rating: 4.5, num_reviews: 2345, features: ['Set of 3', 'Ceramic', 'Drainage Holes'], is_featured: false },
  { name: 'Pressure Cooker - Electric 6qt', description: 'Electric pressure cooker with 6qt capacity, 12 presets, and quick release. Cook meals up to 70% faster. Includes steam rack and recipe book.', price: 69.99, compare_price: 89.99, images: ['https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600'], brand: 'KitchenPro', count_in_stock: 92, rating: 4.5, num_reviews: 6789, features: ['6qt Capacity', '12 Presets', 'Quick Release'], is_featured: false },
  { name: 'Mattress Topper - Memory Foam 3"', description: 'Premium 3-inch gel memory foam mattress topper with cooling technology. Relieves pressure points and adds plush comfort to any mattress.', price: 99.99, compare_price: 149.99, images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600'], brand: 'SleepWell', count_in_stock: 73, rating: 4.6, num_reviews: 9012, features: ['3" Gel Memory Foam', 'Cooling Technology', 'Pressure Relief'], is_featured: false },
  // BOOKS (10 products)
  { name: 'The Art of Programming - Complete Guide', description: 'Comprehensive guide to modern software development. Covers algorithms, data structures, design patterns, and best practices. 1200+ pages.', price: 49.99, compare_price: 69.99, images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600'], brand: 'TechPress', count_in_stock: 200, rating: 4.8, num_reviews: 12345, features: ['1200+ Pages', 'Algorithms & Data Structures', 'Design Patterns'], is_featured: false },
  { name: 'Cooking for Everyone - 500 Recipes', description: 'The ultimate cookbook with 500 easy-to-follow recipes from around the world. Beautiful photography and step-by-step instructions.', price: 29.99, compare_price: 39.99, images: ['https://images.unsplash.com/photo-1589998059171-988d887df646?w=600'], brand: 'CookBook', count_in_stock: 180, rating: 4.6, num_reviews: 8765, features: ['500 Recipes', 'Step-by-Step', 'World Cuisine'], is_featured: false },
  { name: 'Business Strategy - Modern Leadership', description: 'Essential reading for modern business leaders. Covers strategy, innovation, team management, and growth hacking. Includes case studies.', price: 34.99, compare_price: 44.99, images: ['https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=600'], brand: 'BizBooks', count_in_stock: 95, rating: 4.4, num_reviews: 4567, features: ['Case Studies', 'Strategy & Innovation', 'Leadership'], is_featured: false },
  { name: 'The Science of Mindfulness', description: 'Explore the science behind mindfulness and meditation. Evidence-based techniques for reducing stress, improving focus, and finding peace.', price: 19.99, compare_price: 27.99, images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600'], brand: 'MindPress', count_in_stock: 150, rating: 4.5, num_reviews: 6789, features: ['Evidence-Based', 'Stress Reduction', 'Guided Meditations'], is_featured: false },
  { name: 'World History - From Ancient to Modern', description: 'Comprehensive journey through world history from ancient civilizations to the modern era. Illustrated with maps, photos, and timelines.', price: 44.99, compare_price: 59.99, images: ['https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600'], brand: 'EduPress', count_in_stock: 65, rating: 4.7, num_reviews: 3456, features: ['Illustrated', 'Timeline Format', 'Maps & Photos'], is_featured: false },
  { name: 'Fitness for Life - Complete Workout Guide', description: 'Complete fitness guide with workout plans, nutrition advice, and progress tracking. Suitable for all fitness levels from beginner to advanced.', price: 24.99, compare_price: 34.99, images: ['https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600'], brand: 'FitPress', count_in_stock: 120, rating: 4.3, num_reviews: 5678, features: ['Workout Plans', 'Nutrition Guide', 'Progress Tracking'], is_featured: false },
  { name: 'Mystery at Midnight - Thriller Novel', description: 'Gripping thriller novel that will keep you on the edge of your seat. A detective races against time to solve a series of mysterious disappearances.', price: 14.99, compare_price: 22.99, images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600'], brand: 'PageTurner', count_in_stock: 300, rating: 4.2, num_reviews: 12345, features: ['Bestselling Author', '300+ Pages', 'Award Winner'], is_featured: false },
  { name: 'Python Programming - Zero to Hero', description: 'Learn Python programming from scratch. Covers basics to advanced topics including web development, data science, and machine learning.', price: 39.99, compare_price: 54.99, images: ['https://images.unsplash.com/photo-1515879218367-8466d910auj3?w=600'], brand: 'TechPress', count_in_stock: 85, rating: 4.7, num_reviews: 9012, features: ['Python 3', 'Projects Included', 'Data Science'], is_featured: false },
  { name: 'Gardening for Beginners', description: 'Complete guide to starting your own garden. Covers soil preparation, planting, watering, pest control, and harvesting. Great for beginners.', price: 18.99, compare_price: 24.99, images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600'], brand: 'GreenPress', count_in_stock: 110, rating: 4.4, num_reviews: 4567, features: ['Beginner Friendly', 'Seasonal Guide', 'Illustrated'], is_featured: false },
  { name: 'Financial Freedom - Investment Guide', description: 'Achieve financial independence with smart investing strategies. Covers stocks, real estate, crypto, and passive income streams.', price: 27.99, compare_price: 36.99, images: ['https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600'], brand: 'BizBooks', count_in_stock: 75, rating: 4.5, num_reviews: 6789, features: ['Investment Strategies', 'Passive Income', 'Risk Management'], is_featured: false },
  // BEAUTY (11 products)
  { name: 'Organic Skincare Set - Complete Routine', description: 'Complete skincare routine with cleanser, serum, moisturizer, and sunscreen. Made with organic ingredients, suitable for all skin types.', price: 59.99, compare_price: 84.99, images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'], brand: 'GlowNaturals', count_in_stock: 90, rating: 4.4, num_reviews: 5432, features: ['Organic Ingredients', 'Complete Set', 'All Skin Types'], is_featured: true },
  { name: 'Perfume - Eau de Parfum 50ml', description: 'Luxurious eau de parfum with notes of jasmine, vanilla, and sandalwood. Long-lasting fragrance that makes a lasting impression.', price: 79.99, compare_price: 119.99, images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=600'], brand: 'LuxeScents', count_in_stock: 55, rating: 4.6, num_reviews: 3456, features: ['Eau de Parfum', '50ml', 'Long Lasting'], is_featured: false },
  { name: 'Hair Dryer - Ionic Professional', description: 'Professional ionic hair dryer with 1875W power, 3 heat settings, and diffuser attachment. Reduces frizz and drying time by 50%.', price: 44.99, compare_price: 64.99, images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600'], brand: 'StylePro', count_in_stock: 78, rating: 4.3, num_reviews: 5678, features: ['1875W', 'Ionic Technology', 'Diffuser Included'], is_featured: false },
  { name: 'Makeup Brush Set - 12 Piece', description: 'Professional 12-piece makeup brush set with synthetic bristles. Includes brushes for face, eyes, and lips. Comes with travel case.', price: 29.99, compare_price: 44.99, images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'], brand: 'GlowNaturals', count_in_stock: 130, rating: 4.2, num_reviews: 7890, features: ['12 Brushes', 'Synthetic Bristles', 'Travel Case'], is_featured: false },
  { name: 'Face Serum - Vitamin C + Hyaluronic', description: 'Powerful vitamin C serum with hyaluronic acid and vitamin E. Brightens skin, reduces fine lines, and provides deep hydration.', price: 24.99, compare_price: 34.99, images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'], brand: 'GlowNaturals', count_in_stock: 145, rating: 4.5, num_reviews: 9012, features: ['Vitamin C', 'Hyaluronic Acid', 'Brightening'], is_featured: false },
  { name: 'Electric Toothbrush - Sonic Clean', description: 'Sonic electric toothbrush with 5 cleaning modes, 2-minute timer, and USB charging. Removes up to 10x more plaque than manual brushing.', price: 39.99, compare_price: 59.99, images: ['https://images.unsplash.com/photo-1559666126-84f389727b9b?w=600'], brand: 'SmileBright', count_in_stock: 100, rating: 4.4, num_reviews: 6789, features: ['5 Cleaning Modes', 'USB Charging', '2-Minute Timer'], is_featured: false },
  { name: 'Beard Trimmer - Precision Plus', description: 'Professional beard trimmer with 20 length settings, self-sharpening blades, and washable design. Battery lasts 60 minutes.', price: 34.99, compare_price: 49.99, images: ['https://images.unsplash.com/photo-1559666126-84f389727b9b?w=600'], brand: 'StylePro', count_in_stock: 88, rating: 4.3, num_reviews: 4567, features: ['20 Settings', 'Self-Sharpening', 'Washable'], is_featured: false },
  { name: 'Nail Polish Set - 24 Colors', description: 'Set of 24 vibrant nail polish colors in a sleek case. Long-lasting formula with high-shine finish. Perfect for DIY manicures.', price: 19.99, compare_price: 29.99, images: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=600'], brand: 'GlamourNails', count_in_stock: 170, rating: 4.1, num_reviews: 3456, features: ['24 Colors', 'Long Lasting', 'High Shine'], is_featured: false },
  { name: 'Anti-Aging Cream - Retinol Night', description: 'Advanced anti-aging night cream with retinol, peptides, and ceramides. Reduces wrinkles, improves firmness, and renews skin overnight.', price: 49.99, compare_price: 69.99, images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'], brand: 'GlowNaturals', count_in_stock: 62, rating: 4.5, num_reviews: 5678, features: ['Retinol Formula', 'Peptides & Ceramides', 'Night Renewal'], is_featured: false },
  { name: 'Sunscreen SPF 50 - Daily Protection', description: 'Lightweight daily sunscreen with SPF 50, broad-spectrum protection. Non-greasy, water-resistant, and suitable for sensitive skin.', price: 16.99, compare_price: 22.99, images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'], brand: 'GlowNaturals', count_in_stock: 200, rating: 4.2, num_reviews: 7890, features: ['SPF 50', 'Water Resistant', 'Sensitive Skin'], is_featured: false },
  { name: 'Lipstick Set - Matte Collection', description: 'Set of 6 long-wear matte lipsticks in trending shades. Creamy formula that lasts all day without drying your lips.', price: 24.99, compare_price: 34.99, images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'], brand: 'GlamourNails', count_in_stock: 115, rating: 4.3, num_reviews: 4567, features: ['6 Shades', 'Matte Finish', 'Long Wear'], is_featured: false },
  // SPORTS & OUTDOORS (13 products)
  { name: 'Yoga Mat Premium - Extra Thick 6mm', description: 'Extra thick 6mm yoga mat with alignment lines. Non-slip surface, eco-friendly TPE material, includes carrying strap.', price: 34.99, compare_price: 44.99, images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600'], brand: 'FlexFit', count_in_stock: 120, rating: 4.5, num_reviews: 2345, features: ['6mm Thick', 'Non-Slip', 'Eco-Friendly'], is_featured: false },
  { name: 'Adjustable Dumbbell Set - 5-52.5 lbs', description: 'Space-saving adjustable dumbbell set replaces 15 pairs of dumbbells. Quick-change weight system from 5 to 52.5 lbs.', price: 299.99, compare_price: 399.99, images: ['https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=600'], brand: 'FlexFit', count_in_stock: 25, rating: 4.7, num_reviews: 4567, features: ['5-52.5 lbs', 'Replaces 15 Pairs', 'Quick Change'], is_featured: false },
  { name: 'Camping Tent - 4 Person Weatherproof', description: 'Spacious 4-person tent with weatherproof design, easy setup in 5 minutes, and mesh windows for ventilation. Includes carrying bag.', price: 129.99, compare_price: 169.99, images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600'], brand: 'OutdoorPro', count_in_stock: 38, rating: 4.4, num_reviews: 3456, features: ['4 Person', '5-Min Setup', 'Weatherproof'], is_featured: false },
  { name: 'Mountain Bike - 21 Speed Full Suspension', description: 'Full suspension mountain bike with 21-speed Shimano gears, disc brakes, and durable aluminum frame. Perfect for trails and commuting.', price: 349.99, compare_price: 499.99, images: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=600'], brand: 'TrailBlazer', count_in_stock: 15, rating: 4.5, num_reviews: 2345, features: ['21-Speed', 'Full Suspension', 'Disc Brakes'], is_featured: false },
  { name: 'Resistance Bands Set - 5 Levels', description: 'Set of 5 resistance bands with different tension levels. Includes door anchor, ankle straps, and carrying bag. Perfect for home workouts.', price: 19.99, compare_price: 29.99, images: ['https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=600'], brand: 'FlexFit', count_in_stock: 200, rating: 4.3, num_reviews: 12345, features: ['5 Resistance Levels', 'Door Anchor', 'Carrying Bag'], is_featured: false },
  { name: 'Running Belt - Phone Holder', description: 'Lightweight running belt with expandable pocket fits all phones. Reflective strip for safety, moisture-wicking material, and bounce-free design.', price: 14.99, compare_price: 19.99, images: ['https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600'], brand: 'FlexFit', count_in_stock: 180, rating: 4.2, num_reviews: 6789, features: ['Fits All Phones', 'Reflective', 'Bounce-Free'], is_featured: false },
  { name: 'Hiking Backpack - 40L Waterproof', description: 'Durable 40L hiking backpack with rain cover, hydration sleeve, and multiple compartments. Ergonomic design with padded hip belt.', price: 64.99, compare_price: 84.99, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'], brand: 'OutdoorPro', count_in_stock: 68, rating: 4.5, num_reviews: 4567, features: ['40L Capacity', 'Rain Cover', 'Hydration Sleeve'], is_featured: false },
  { name: 'Jump Rope - Speed Cable Pro', description: 'Professional speed jump rope with ball bearing system for smooth rotation. Adjustable cable length. Perfect for HIIT and boxing training.', price: 12.99, compare_price: 17.99, images: ['https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600'], brand: 'FlexFit', count_in_stock: 250, rating: 4.4, num_reviews: 5678, features: ['Ball Bearing', 'Adjustable', 'Lightweight'], is_featured: false },
  { name: 'Water Bottle - Insulated 32oz', description: 'Double-wall vacuum insulated water bottle keeps drinks cold 24hrs or hot 12hrs. 32oz capacity, leak-proof lid, and wide mouth.', price: 24.99, compare_price: 34.99, images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600'], brand: 'OutdoorPro', count_in_stock: 190, rating: 4.6, num_reviews: 9012, features: ['32oz', '24hr Cold', 'Leak Proof'], is_featured: false },
  { name: 'Foam Roller - Muscle Recovery', description: 'High-density foam roller for muscle recovery and myofascial release. 18 inches long, firm density. Includes exercise guide.', price: 19.99, compare_price: 27.99, images: ['https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=600'], brand: 'FlexFit', count_in_stock: 95, rating: 4.3, num_reviews: 4567, features: ['High Density', '18 Inches', 'Exercise Guide'], is_featured: false },
  { name: 'Cooler - 45 Quart Wheeled', description: 'Heavy-duty 45-quart cooler with wheels and telescoping handle. Keeps ice up to 5 days. Bear-resistant design for camping trips.', price: 89.99, compare_price: 129.99, images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600'], brand: 'OutdoorPro', count_in_stock: 42, rating: 4.6, num_reviews: 6789, features: ['45 Quart', '5-Day Ice Retention', 'Bear Resistant'], is_featured: false },
  { name: 'Golf Club Set - Complete 12 Piece', description: 'Complete 12-piece golf club set including driver, irons, wedges, putter, and stand bag. Premium graphite shafts, suitable for all skill levels.', price: 399.99, compare_price: 549.99, images: ['https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=600'], brand: 'ProSwing', count_in_stock: 18, rating: 4.4, num_reviews: 2345, features: ['12-Piece Set', 'Graphite Shafts', 'Stand Bag'], is_featured: false },
  { name: 'Kayak - Inflatable 2 Person', description: 'Durable inflatable kayak for 2 people with included paddles and pump. Portable design fits in a backpack. Perfect for lakes and calm rivers.', price: 199.99, compare_price: 279.99, images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600'], brand: 'OutdoorPro', count_in_stock: 22, rating: 4.3, num_reviews: 3456, features: ['2 Person', 'Includes Pump', 'Backpack Size'], is_featured: false },
  // TOYS & GAMES (13 products)
  { name: 'Building Blocks Set - 1500 Pieces', description: 'Creative building blocks set with 1500 pieces in various colors and shapes. Compatible with all major brands. Includes storage box.', price: 39.99, compare_price: 54.99, images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600'], brand: 'KidStuff', count_in_stock: 85, rating: 4.7, num_reviews: 12345, features: ['1500 Pieces', 'Storage Box', 'Compatible'], is_featured: false },
  { name: 'Remote Control Car - Off Road RC Truck', description: 'Powerful remote control monster truck with 4WD, LED lights, and rechargeable battery. Runs 30 minutes per charge. Speeds up to 20mph.', price: 49.99, compare_price: 69.99, images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600'], brand: 'RCTech', count_in_stock: 60, rating: 4.4, num_reviews: 5678, features: ['4WD', '20mph', 'Rechargeable'], is_featured: false },
  { name: 'Board Game - Strategy Collection', description: 'Award-winning strategy board game for 2-6 players. Average playtime 60-90 minutes. Easy to learn, hard to master. Perfect family game night.', price: 34.99, compare_price: 44.99, images: ['https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600'], brand: 'GameNight', count_in_stock: 95, rating: 4.6, num_reviews: 8901, features: ['2-6 Players', '60-90 Min', 'Strategy Game'], is_featured: false },
  { name: 'Drone with Camera - 4K HD', description: 'Foldable drone with 4K camera, GPS positioning, and 30-minute flight time. One-key return, follow me mode, and gesture control.', price: 299.99, compare_price: 399.99, images: ['https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=600'], brand: 'SkyView', count_in_stock: 28, rating: 4.5, num_reviews: 3456, features: ['4K Camera', 'GPS Positioning', '30min Flight'], is_featured: false },
  { name: 'Science Kit - 50 Experiments', description: 'Educational science kit with 50 fun experiments for kids aged 8-14. Includes chemicals, lab equipment, and instruction manual.', price: 29.99, compare_price: 39.99, images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600'], brand: 'KidStuff', count_in_stock: 72, rating: 4.5, num_reviews: 6789, features: ['50 Experiments', 'Ages 8-14', 'Lab Equipment'], is_featured: false },
  { name: 'Plush Teddy Bear - Giant 48"', description: 'Gigantic 48-inch plush teddy bear. Ultra-soft material, hypoallergenic filling, and machine washable. Perfect gift for all ages.', price: 59.99, compare_price: 79.99, images: ['https://images.unsplash.com/photo-1545404537-a526c852e3d7?w=600'], brand: 'KidStuff', count_in_stock: 40, rating: 4.8, num_reviews: 4567, features: ['48 Inches', 'Ultra-Soft', 'Machine Washable'], is_featured: false },
  { name: 'Video Game - Open World Adventure', description: 'Epic open-world adventure game with stunning graphics, 100+ hours of gameplay, and multiplayer mode. Rated E for Everyone.', price: 59.99, compare_price: 69.99, images: ['https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600'], brand: 'GameTech', count_in_stock: 500, rating: 4.7, num_reviews: 56789, features: ['Open World', '100+ Hours', 'Multiplayer'], is_featured: false },
  { name: 'Puzzle - 2000 Piece Jigsaw', description: 'Challenging 2000-piece jigsaw puzzle featuring a beautiful landscape scene. Premium quality with anti-glare surface and exact fit pieces.', price: 24.99, compare_price: 34.99, images: ['https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600'], brand: 'GameNight', count_in_stock: 65, rating: 4.3, num_reviews: 3456, features: ['2000 Pieces', 'Anti-Glare', 'Premium Quality'], is_featured: false },
  { name: 'Nerf Blaster - Motorized 100 Darts', description: 'Motorized Nerf blaster that shoots up to 100 darts with 10-dart clip. Includes 100 darts, 10 clips, and tactical vest. Ages 8+.', price: 44.99, compare_price: 59.99, images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600'], brand: 'KidStuff', count_in_stock: 55, rating: 4.4, num_reviews: 6789, features: ['Motorized', '100 Darts', '10 Clips'], is_featured: false },
  { name: 'Electric Scooter - Foldable 15mph', description: 'Foldable electric scooter with 15mph top speed, 15-mile range, and LED display. Lightweight aluminum frame, quick fold for portability.', price: 249.99, compare_price: 349.99, images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600'], brand: 'RideEasy', count_in_stock: 33, rating: 4.3, num_reviews: 4567, features: ['15mph', '15 Mile Range', 'Foldable'], is_featured: false },
  { name: 'Musical Keyboard - 61 Keys', description: '61-key electronic keyboard with touch response, 200 sounds, 200 rhythms, and learning system. Headphone jack for silent practice.', price: 89.99, compare_price: 129.99, images: ['https://images.unsplash.com/photo-1558531305-e6946bf677c8?w=600'], brand: 'MusicWorld', count_in_stock: 48, rating: 4.5, num_reviews: 5678, features: ['61 Keys', '200 Sounds', 'Learning System'], is_featured: false },
  { name: 'Robot Toy - Programmable STEM', description: 'Programmable robot toy with LED matrix, sensors, and drag-and-drop coding app. Teaches STEM concepts through fun activities. Ages 8+.', price: 79.99, compare_price: 99.99, images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600'], brand: 'KidStuff', count_in_stock: 45, rating: 4.6, num_reviews: 3456, features: ['Programmable', 'STEM Learning', 'App Controlled'], is_featured: false },
  { name: 'Trampoline - 10ft Outdoor with Enclosure', description: '10-foot outdoor trampoline with safety enclosure, weather-resistant jumping mat, and rust-resistant frame. Supports up to 250 lbs.', price: 199.99, compare_price: 279.99, images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600'], brand: 'KidStuff', count_in_stock: 20, rating: 4.4, num_reviews: 5678, features: ['10ft Diameter', 'Safety Enclosure', '250lb Capacity'], is_featured: false },
];

async function seedProducts() {
  const { count } = await supabase.from('products').select('*', { count: 'exact', head: true });
  if (count && count >= 100) {
    console.log(`Already have ${count} products. Skipping seed.`);
    return;
  }

  const { data: categories } = await supabase.from('categories').select('*');
  if (!categories || categories.length === 0) {
    console.log('No categories found. Run the main seed first.');
    return;
  }

  const catMap: Record<string, string> = {};
  categories.forEach((c: any) => { catMap[c.slug] = c.id; });

  const catSlug = (idx: number): string => {
    if (idx < 20) return 'electronics';
    if (idx < 37) return 'fashion';
    if (idx < 53) return 'home-kitchen';
    if (idx < 63) return 'books';
    if (idx < 74) return 'beauty';
    if (idx < 87) return 'sports-outdoors';
    return 'electronics';
  };

  const existingCount = count || 0;
  const toInsert = products.slice(existingCount);

  if (toInsert.length === 0) {
    console.log('All products already seeded.');
    return;
  }

  const batch = toInsert.map((p: any, i: number) => ({
    ...p,
    category_id: catMap[catSlug(existingCount + i)],
    created_at: new Date(Date.now() - Math.random() * 365 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  }));

  const { error } = await supabase.from('products').insert(batch);
  if (error) {
    console.error('Seed error:', error);
    return;
  }

  console.log(`Added ${batch.length} products! Total: ${(count || 0) + batch.length}`);
}

seedProducts().catch(console.error);
